version: '2'

services:

  celery:
    restart: always
    image: tbackman/debian-cheminformatics:debian10-update2
    volumes:
      - .:/clusterCAD
      - /www/static
      - /www/media
    depends_on:
        - db
        - redis
        - web
    working_dir: /clusterCAD

    command: [celery, -A, clusterCAD, worker, -l, info, --loglevel=INFO]

  celery-beat:
    restart: always
    image: tbackman/debian-cheminformatics:debian10-update2
    volumes:
      - .:/clusterCAD
      - /www/static
      - /www/media
    depends_on:
        - db
        - redis
        - web
    working_dir: /clusterCAD

    command: [celery, -A, clusterCAD, beat, -l, info, --loglevel=INFO, --pidfile=]
    
  db:
    user: postgres
    # postgres internal port is 5432
    restart: always
    image: tbackman/debian-cheminformatics:debian10-update2
    command: ["/usr/lib/postgresql/11/bin/postgres", "-D", "/var/lib/postgresql/11/main", "-c", "config_file=/etc/postgresql/11/main/postgresql.conf"]
    volumes:
      - app-db-data:/var/lib/postgresql/11/main

  redis:
    restart: always
    image: redis:3.2-alpine 

  # this is ClusterCAD
  web:
    restart: always
    image: tbackman/debian-cheminformatics:debian10-update2
    volumes:
      - .:/clusterCAD
      - static:/www/static
      - media:/www/media
    expose:
      - "8000"
    ports:
      - "8888:8888"
    depends_on:
      - db
      - redis
    working_dir: /clusterCAD
    command: ["./wait-for-it.sh", "db:5432", "--", "./entrypoint.sh"]

  nginx:
    restart: always
    build: ./nginx/
    ports:
      - "8000:80"
    volumes:
      - static:/www/static
      - media:/www/media
    links:
      - web:web

  react:
    build:
      context: retrotide
      dockerfile: Dockerfile
    volumes: 
      - .:/retrotide/app
      - /retrotide/app/node_modules
    ports:
      - "3000:3000"
    environment:
      # attempting hot-reload fix
      - CHOKIDAR_USEPOLLING=true
      - NODE_ENV=development
    command: npm start

volumes:
  app-db-data:
  static:
  media:
